image: mhart/alpine-node

build:
  stage: build
  script:
    - apk add --no-cache git
    - npm install
  artifacts:
    paths:
      - public
    expire_in: 1 day

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - coverage/coverage-final.json