image: alpine:latest

stages:
  - build app
  - test
  - build image

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375


build:
  stage: build app
  image: mhart/alpine-node
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build
      - node_modules

test:
  stage: test
  image: mhart/alpine-node
  script:
    - npm test
  artifacts:
    paths:
      - coverage/coverage-final.json

build_image:
  stage: build image
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/ui:latest
    - docker push $CI_REGISTRY_IMAGE/ui:latest
